// BlitzSeller - Dados mock para desenvolvimento
import type { User, Quest, Achievement, Lead, RejectionScenario, DashboardStats } from "./types"

export const registeredUsers: Array<{ email: string; password: string; userData: User }> = [
  {
    email: "elias.serrano.fagundes@gmail.com",
    password: "teste123",
    userData: {
      id: "admin-1",
      name: "Elias Serrano Fagundes",
      email: "elias.serrano.fagundes@gmail.com",
      avatar: "/professional-avatar.png",
      level: 10,
      xp: 5000,
      coins: 500,
      streak: 30,
      joinedAt: new Date("2024-01-01").toISOString(),
      lastActiveAt: new Date().toISOString(),
      role: "admin",
      primarySegment: "door-to-door",
      secondarySegment: "medical-business",
      geographicArea: "São Paulo - SP",
    },
  },
]

export const mockUser: User = {
  id: "1",
  name: "João Silva",
  email: "joao@exemplo.com",
  avatar: "/professional-avatar.png",
  level: 5,
  xp: 2450,
  coins: 180,
  streak: 7,
  joinedAt: new Date("2024-01-15").toISOString(),
  lastActiveAt: new Date().toISOString(),
}

export const mockQuests: Quest[] = [
  {
    id: "1",
    title: "Fazer 5 ligações hoje",
    description: "Complete 5 ligações para prospects qualificados",
    type: "daily",
    xpReward: 50,
    coinReward: 10,
    difficulty: "easy",
    category: "calls",
    completed: false,
    targetValue: 5,
    currentValue: 2,
  },
  {
    id: "2",
    title: "Agendar 2 reuniões",
    description: "Agende pelo menos 2 reuniões com prospects interessados",
    type: "daily",
    xpReward: 100,
    coinReward: 20,
    difficulty: "medium",
    category: "meetings",
    completed: false,
    targetValue: 2,
    currentValue: 0,
  },
  {
    id: "3",
    title: "Prospectar 10 novos leads",
    description: "Adicione 10 novos leads qualificados ao seu pipeline",
    type: "daily",
    xpReward: 75,
    coinReward: 15,
    difficulty: "medium",
    category: "prospecting",
    completed: true,
    completedAt: new Date("2024-01-20").toISOString(),
    targetValue: 10,
    currentValue: 10,
  },
]

export const mockAchievements: Achievement[] = [
  {
    id: "1",
    title: "Primeiro Fechamento",
    description: "Feche sua primeira venda",
    icon: "🎯",
    xpReward: 200,
    coinReward: 50,
    unlocked: true,
    unlockedAt: new Date("2024-01-20").toISOString(),
    category: "sales",
  },
  {
    id: "2",
    title: "Sequência de 7 dias",
    description: "Complete quests por 7 dias consecutivos",
    icon: "🔥",
    xpReward: 150,
    coinReward: 30,
    unlocked: true,
    unlockedAt: new Date().toISOString(),
    category: "streak",
  },
  {
    id: "3",
    title: "Mestre das Ligações",
    description: "Complete 100 ligações",
    icon: "📞",
    xpReward: 300,
    coinReward: 75,
    unlocked: false,
    category: "activity",
  },
]

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Maria Santos",
    email: "maria@empresa.com",
    phone: "(11) 99999-9999",
    company: "Tech Solutions Ltda",
    status: "hot",
    source: "LinkedIn",
    value: 15000,
    probability: 80,
    lastContact: new Date("2024-01-25").toISOString(),
    nextFollowUp: new Date("2024-01-28").toISOString(),
    notes: ["Interessada na solução premium", "Orçamento aprovado"],
    tags: ["premium", "tech"],
    createdAt: new Date("2024-01-20").toISOString(),
    updatedAt: new Date("2024-01-25").toISOString(),
  },
  {
    id: "2",
    name: "Carlos Oliveira",
    email: "carlos@startup.com",
    phone: "(11) 88888-8888",
    company: "StartupXYZ",
    status: "warm",
    source: "Indicação",
    value: 8000,
    probability: 60,
    lastContact: new Date("2024-01-24").toISOString(),
    nextFollowUp: new Date("2024-01-29").toISOString(),
    notes: ["Precisa de aprovação do sócio"],
    tags: ["startup", "indicação"],
    createdAt: new Date("2024-01-18").toISOString(),
    updatedAt: new Date("2024-01-24").toISOString(),
  },
]

export const mockRejectionScenarios: RejectionScenario[] = [
  {
    id: "1",
    title: "Objeção de Preço",
    description: "Cliente diz que o preço está muito alto",
    difficulty: "beginner",
    category: "price",
    scenario: 'O cliente responde: "Achei muito caro, não temos orçamento para isso agora."',
    suggestedResponses: [
      "Entendo sua preocupação. Vamos conversar sobre o valor que nossa solução pode gerar para sua empresa.",
      "Que tal avaliarmos opções de pagamento que se adequem ao seu orçamento atual?",
      "Posso mostrar como outros clientes conseguiram ROI positivo em poucos meses?",
    ],
    tips: [
      "Foque no valor, não no preço",
      "Pergunte sobre o custo de não resolver o problema",
      "Ofereça opções de pagamento flexíveis",
    ],
    completed: false,
  },
  {
    id: "2",
    title: "Falta de Autoridade",
    description: "Pessoa não tem poder de decisão",
    difficulty: "intermediate",
    category: "authority",
    scenario: 'O prospect diz: "Preciso conversar com meu chefe antes de decidir qualquer coisa."',
    suggestedResponses: [
      "Perfeito! Que tal agendarmos uma reunião com vocês dois para que eu possa esclarecer todas as dúvidas?",
      "Entendo. Quais são as principais preocupações que seu chefe costuma ter nesse tipo de decisão?",
      "Posso preparar um material específico para ajudar na sua apresentação para ele?",
    ],
    tips: [
      "Identifique o decisor real desde o início",
      "Ofereça-se para participar da conversa",
      "Prepare materiais de apoio",
    ],
    completed: true,
    score: 85,
    completedAt: new Date("2024-01-23").toISOString(),
  },
]

export const mockDashboardStats: DashboardStats = {
  totalLeads: 45,
  activeLeads: 23,
  closedDeals: 8,
  revenue: 120000,
  conversionRate: 17.8,
  averageDealSize: 15000,
  activitiesThisWeek: 28,
  callsToday: 5,
  meetingsScheduled: 3,
  streak: 7,
}
